apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: efk
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      # initContainers:
        # - name: set-permissions
          # image: registry.hub.docker.com/library/busybox:latest
          # command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/config/elasticsearch.keystore']
          # securityContext:
            # runAsUser: 0
          # volumeMounts:
            # - mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
              # name: elasticsearch-keystore
      containers:
      - name: elasticsearch
        image: elasticsearch:7.9.0
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        volumeMounts:
          - name: elasticsearch-config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          # - name: elasticsearch-keystore
            # mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
        # - name: elasticsearch-keystore
          # hostPath:
            # path: /run/desktop/mnt/host/c/personal/Richa/efk/workspace-kibana-spaces/new-version/elasticsearch.keystore
---
apiVersion: v1
kind: Service
metadata:
  name: es-nodeport
  namespace: efk
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31200