apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: efk
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5601
    nodePort: 31141
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.9.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          # - name: ELASTICSEARCH_USERNAME
            # value: kibana_system
          # - name: ELASTICSEARCH_PASSWORD
            # value: kibana_system
        ports:
        - containerPort: 5601